from __future__ import annotations

from typing import Any


ODOO_MAPPING: dict[str, dict[str, Any]] = {
    "catalog": {
        "interface": "catalogue`, filtres, liste produits",
        "odoo_model": "product.template",
        "odoo_fields": [
            "id",
            "name",
            "default_code",
            "description_sale",
            "list_price",
            "website_published",
            "categ_id",
            "image_1920",
            "sale_ok",
            "active",
            "product_variant_count",
        ],
        "transformation": "normalisation des produits vers un payload frontend",
        "business_rule": "Afficher uniquement les produits publiés, actifs et vendables",
    },
    "product_detail": {
        "interface": "fiche produit",
        "odoo_model": "product.template",
        "odoo_fields": [
            "id",
            "name",
            "description",
            "description_sale",
            "list_price",
            "standard_price",
            "image_1920",
            "website_published",
            "categ_id",
            "attribute_line_ids",
            "product_variant_ids",
        ],
        "transformation": "fusion des variantes et des attributs product/product.template",
        "business_rule": "Ne pas afficher le produit si non publié ou hors stock en rupture",
    },
    "pricing": {
        "interface": "prix, promotions, listes de prix",
        "odoo_model": "product.pricelist.item",
        "odoo_fields": [
            "pricelist_id",
            "product_tmpl_id",
            "product_id",
            "price_surcharge",
            "price_discount",
            "compute_price",
            "fixed_price",
            "min_quantity",
        ],
        "transformation": "calcul du prix final selon la liste active et les remises",
        "business_rule": "Appliquer la règle de priorité des listes de prix Odoo",
    },
    "stock": {
        "interface": "stock, disponibilité, rupture",
        "odoo_model": "stock.quant",
        "odoo_fields": [
            "product_id",
            "location_id",
            "quantity",
            "reserved_quantity",
            "available_quantity",
        ],
        "transformation": "calcul de la disponibilité réelle au moment du parcours",
        "business_rule": "Bloquer l’achat si quantity <= 0 et stock non dispo",
    },
    "cart": {
        "interface": "panier",
        "odoo_model": "sale.order.line",
        "odoo_fields": [
            "order_id",
            "product_id",
            "product_uom_qty",
            "price_unit",
            "price_subtotal",
            "discount",
        ],
        "transformation": "transfert du panier dans une commande en cours",
        "business_rule": "Un panier ne peut pas contenir d’article indisponible",
    },
    "customer": {
        "interface": "compte client, adresse",
        "odoo_model": "res.partner",
        "odoo_fields": [
            "id",
            "name",
            "email",
            "phone",
            "street",
            "city",
            "zip",
            "country_id",
        ],
        "transformation": "normalisation du profil et des adresses live",
        "business_rule": "Chaque commande doit être rattachée à un client correctement identifié",
    },
    "order": {
        "interface": "commande, confirmation",
        "odoo_model": "sale.order",
        "odoo_fields": [
            "id",
            "name",
            "partner_id",
            "state",
            "amount_total",
            "date_order",
            "warehouse_id",
        ],
        "transformation": "conversion du panier en commande Odoo",
        "business_rule": "Créer la commande uniquement après validation du panier et du client",
    },
    "invoice": {
        "interface": "facturation",
        "odoo_model": "account.move",
        "odoo_fields": [
            "id",
            "partner_id",
            "invoice_date",
            "amount_total",
            "state",
        ],
        "transformation": "génération de la facture après validation de commande",
        "business_rule": "La facture ne peut être créée qu’après la confirmation de vente",
    },
}
